### PR TITLE
Added ashwinganesh.json to git demo

### PR DESCRIPTION
**Pull request by aganesh10**

### CODE REVIEW

**Comment by MrMinos** [comment]
Please make the PR title relevant.

**Review by tbliu — APPROVED** [review]
lgtm

**Review by MrMinos — CHANGES_REQUESTED** [review]
Please fix PR title

**Review by tbliu — APPROVED** [review]
lgtm again

**Review by MrMinos — APPROVED** [review]

**Comment by MrMinos** [comment]
@tbliu with lightning PR review haha

**Pull request merged**
